# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Briq' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Briq
    pod 'Alamofire', '~> 4.4'
    pod 'RappleProgressHUD'
    pod 'FacebookCore'
pod 'FacebookLogin'

  target 'BriqTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BriqUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
